### ISSUE TITLE
Errore in creazione di branch per pull request

### ISSUE THREAD

**Issue by Jeanluc74** [italia/spid-ruby#66]
Buongiorno,

come da https://github.com/italia/spid-rails/issues/31 ho tentato di creare un branch in questo repository per creare una pull request, ma mi restituisce:

remote: Permission to italia/spid-ruby.git denied to Jeanluc74.
fatal: unable to access 'https://github.com/italia/spid-ruby/': The requested URL returned error: 403

Ho dato uno sguardo su https://github.com/trilbymedia/grav-plugin-git-sync/issues/39 e tentato anche l'autenticazione con token senza esito.

Potreste dare un'occhiata per verificare se il repository prevede la necessità di autorizzare esplicitamente la creazione di branch? Nel caso autorizzereste la mia utenza?

Grazie

Gian Luca

**Comment by ruphy** [comment]
Ciao Gian Luca,

per aprire una pull request non ti serve avere accesso in scrittura a questo repository! Ti basta [fare un fork personale](https://help.github.com/en/articles/fork-a-repo) di questo repository, sul quale avrai tutti i permessi, ed aprire una pull request dall'interfaccia web! Ti suggerisco anche il seguente articolo: https://help.github.com/en/articles/about-pull-requests

Ciao,
Riccardo

**Comment by Jeanluc74** [comment]
Bene, grazie!
